// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: konstellation/compliance/v1/compliance.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// List identifies one of the two compliance lists.
type List int32

const (
	// LIST_UNSPECIFIED is invalid.
	LIST_UNSPECIFIED List = 0
	// LIST_ALLOW is the "verified" list. Never enforced by the chain; exposed to
	// contracts through the precompile so they can opt in.
	LIST_ALLOW List = 1
	// LIST_BLOCK is the "frozen" list. Enforced chain-wide by the ante handler:
	// no transaction signed by, paying for, or directly transferring to a listed
	// address is accepted.
	LIST_BLOCK List = 2
)

var List_name = map[int32]string{
	0: "LIST_UNSPECIFIED",
	1: "LIST_ALLOW",
	2: "LIST_BLOCK",
}

var List_value = map[string]int32{
	"LIST_UNSPECIFIED": 0,
	"LIST_ALLOW":       1,
	"LIST_BLOCK":       2,
}

func (x List) String() string {
	return proto.EnumName(List_name, int32(x))
}

func (List) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{0}
}

// Action is what a Change does to a list.
type Action int32

const (
	// ACTION_UNSPECIFIED is invalid.
	ACTION_UNSPECIFIED Action = 0
	// ACTION_ADD adds the address to the list.
	ACTION_ADD Action = 1
	// ACTION_REMOVE removes the address from the list.
	ACTION_REMOVE Action = 2
)

var Action_name = map[int32]string{
	0: "ACTION_UNSPECIFIED",
	1: "ACTION_ADD",
	2: "ACTION_REMOVE",
}

var Action_value = map[string]int32{
	"ACTION_UNSPECIFIED": 0,
	"ACTION_ADD":         1,
	"ACTION_REMOVE":      2,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{1}
}

// Params are the module parameters. All changes are governance-only.
type Params struct {
	// authority is the address (bech32) allowed to schedule updates and to
	// emergency-freeze. Empty means no such authority exists and only
	// governance can change the lists. Intended to be a foundation multisig.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// timelock is the delay between an authority scheduling a change and the
	// change taking effect, and the lifetime of an emergency freeze that is not
	// ratified. Also the notice period a scheduled change can be cancelled in.
	Timelock time.Duration `protobuf:"bytes,2,opt,name=timelock,proto3,stdduration" json:"timelock"`
	// allowlist_add_timelock is the delay for adding an address to the allow
	// list only. Kept separate because it gates onboarding latency, not safety.
	AllowlistAddTimelock time.Duration `protobuf:"bytes,3,opt,name=allowlist_add_timelock,json=allowlistAddTimelock,proto3,stdduration" json:"allowlist_add_timelock"`
	// enforce switches the ante-handler check on and off. Governance kill
	// switch; the lists and the precompile keep working when it is off.
	Enforce bool `protobuf:"varint,4,opt,name=enforce,proto3" json:"enforce,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Params) GetTimelock() time.Duration {
	if m != nil {
		return m.Timelock
	}
	return 0
}

func (m *Params) GetAllowlistAddTimelock() time.Duration {
	if m != nil {
		return m.AllowlistAddTimelock
	}
	return 0
}

func (m *Params) GetEnforce() bool {
	if m != nil {
		return m.Enforce
	}
	return false
}

// ListEntry is one address on one list.
type ListEntry struct {
	// address in bech32.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	List    List   `protobuf:"varint,2,opt,name=list,proto3,enum=konstellation.compliance.v1.List" json:"list,omitempty"`
	// added_at is the block time the entry took effect.
	AddedAt time.Time `protobuf:"bytes,3,opt,name=added_at,json=addedAt,proto3,stdtime" json:"added_at"`
	// expires_at is set only for an emergency freeze: the block time after
	// which the entry is dropped unless a permanent entry replaced it. Nil is
	// permanent.
	ExpiresAt *time.Time `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,stdtime" json:"expires_at,omitempty"`
	// reason is the public justification recorded with the entry.
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *ListEntry) Reset()         { *m = ListEntry{} }
func (m *ListEntry) String() string { return proto.CompactTextString(m) }
func (*ListEntry) ProtoMessage()    {}
func (*ListEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{1}
}
func (m *ListEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEntry.Merge(m, src)
}
func (m *ListEntry) XXX_Size() int {
	return m.Size()
}
func (m *ListEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ListEntry proto.InternalMessageInfo

func (m *ListEntry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ListEntry) GetList() List {
	if m != nil {
		return m.List
	}
	return LIST_UNSPECIFIED
}

func (m *ListEntry) GetAddedAt() time.Time {
	if m != nil {
		return m.AddedAt
	}
	return time.Time{}
}

func (m *ListEntry) GetExpiresAt() *time.Time {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *ListEntry) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// Change is one add/remove on one list, the unit of a scheduled update.
type Change struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	List    List   `protobuf:"varint,2,opt,name=list,proto3,enum=konstellation.compliance.v1.List" json:"list,omitempty"`
	Action  Action `protobuf:"varint,3,opt,name=action,proto3,enum=konstellation.compliance.v1.Action" json:"action,omitempty"`
	Reason  string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{2}
}
func (m *Change) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Change.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return m.Size()
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Change) GetList() List {
	if m != nil {
		return m.List
	}
	return LIST_UNSPECIFIED
}

func (m *Change) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return ACTION_UNSPECIFIED
}

func (m *Change) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// PendingUpdate is a scheduled set of changes waiting out its timelock.
type PendingUpdate struct {
	Id      uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Changes []Change `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes"`
	// execute_at is the block time at or after which EndBlock applies it.
	ExecuteAt time.Time `protobuf:"bytes,3,opt,name=execute_at,json=executeAt,proto3,stdtime" json:"execute_at"`
	// scheduled_by is the authority that scheduled it.
	ScheduledBy string `protobuf:"bytes,4,opt,name=scheduled_by,json=scheduledBy,proto3" json:"scheduled_by,omitempty"`
	// extended lists the emergency freezes that scheduling this update pushed
	// out to execute_at (a scheduled permanent block ratifies a live emergency
	// freeze). Cancelling the update restores each to its original expiry, so
	// schedule-then-cancel cannot keep an address frozen past one timelock.
	Extended []ExtendedFreeze `protobuf:"bytes,5,rep,name=extended,proto3" json:"extended"`
}

func (m *PendingUpdate) Reset()         { *m = PendingUpdate{} }
func (m *PendingUpdate) String() string { return proto.CompactTextString(m) }
func (*PendingUpdate) ProtoMessage()    {}
func (*PendingUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{3}
}
func (m *PendingUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingUpdate.Merge(m, src)
}
func (m *PendingUpdate) XXX_Size() int {
	return m.Size()
}
func (m *PendingUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PendingUpdate proto.InternalMessageInfo

func (m *PendingUpdate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PendingUpdate) GetChanges() []Change {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *PendingUpdate) GetExecuteAt() time.Time {
	if m != nil {
		return m.ExecuteAt
	}
	return time.Time{}
}

func (m *PendingUpdate) GetScheduledBy() string {
	if m != nil {
		return m.ScheduledBy
	}
	return ""
}

func (m *PendingUpdate) GetExtended() []ExtendedFreeze {
	if m != nil {
		return m.Extended
	}
	return nil
}

// ExtendedFreeze records the expiry an emergency freeze had before a
// scheduled update extended it.
type ExtendedFreeze struct {
	Address           string    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OriginalExpiresAt time.Time `protobuf:"bytes,2,opt,name=original_expires_at,json=originalExpiresAt,proto3,stdtime" json:"original_expires_at"`
}

func (m *ExtendedFreeze) Reset()         { *m = ExtendedFreeze{} }
func (m *ExtendedFreeze) String() string { return proto.CompactTextString(m) }
func (*ExtendedFreeze) ProtoMessage()    {}
func (*ExtendedFreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{4}
}
func (m *ExtendedFreeze) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExtendedFreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExtendedFreeze.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExtendedFreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendedFreeze.Merge(m, src)
}
func (m *ExtendedFreeze) XXX_Size() int {
	return m.Size()
}
func (m *ExtendedFreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendedFreeze.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendedFreeze proto.InternalMessageInfo

func (m *ExtendedFreeze) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ExtendedFreeze) GetOriginalExpiresAt() time.Time {
	if m != nil {
		return m.OriginalExpiresAt
	}
	return time.Time{}
}

// Cooldown records that an address may not be emergency-frozen again before
// `until`: one timelock after its last emergency freeze lapsed or was lifted.
type Cooldown struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// until is a unix time in seconds.
	Until int64 `protobuf:"varint,2,opt,name=until,proto3" json:"until,omitempty"`
}

func (m *Cooldown) Reset()         { *m = Cooldown{} }
func (m *Cooldown) String() string { return proto.CompactTextString(m) }
func (*Cooldown) ProtoMessage()    {}
func (*Cooldown) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e1bde5561c267f4, []int{5}
}
func (m *Cooldown) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Cooldown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Cooldown.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Cooldown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cooldown.Merge(m, src)
}
func (m *Cooldown) XXX_Size() int {
	return m.Size()
}
func (m *Cooldown) XXX_DiscardUnknown() {
	xxx_messageInfo_Cooldown.DiscardUnknown(m)
}

var xxx_messageInfo_Cooldown proto.InternalMessageInfo

func (m *Cooldown) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Cooldown) GetUntil() int64 {
	if m != nil {
		return m.Until
	}
	return 0
}

func init() {
	proto.RegisterEnum("konstellation.compliance.v1.List", List_name, List_value)
	proto.RegisterEnum("konstellation.compliance.v1.Action", Action_name, Action_value)
	proto.RegisterType((*Params)(nil), "konstellation.compliance.v1.Params")
	proto.RegisterType((*ListEntry)(nil), "konstellation.compliance.v1.ListEntry")
	proto.RegisterType((*Change)(nil), "konstellation.compliance.v1.Change")
	proto.RegisterType((*PendingUpdate)(nil), "konstellation.compliance.v1.PendingUpdate")
	proto.RegisterType((*ExtendedFreeze)(nil), "konstellation.compliance.v1.ExtendedFreeze")
	proto.RegisterType((*Cooldown)(nil), "konstellation.compliance.v1.Cooldown")
}

func init() {
	proto.RegisterFile("konstellation/compliance/v1/compliance.proto", fileDescriptor_8e1bde5561c267f4)
}

var fileDescriptor_8e1bde5561c267f4 = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xbb, 0x6e, 0x13, 0x41,
	0x14, 0xf5, 0x6e, 0x36, 0x7e, 0x4c, 0x88, 0xe5, 0x0c, 0x56, 0xb4, 0x31, 0xd2, 0xda, 0x98, 0xc6,
	0x0a, 0xc4, 0x56, 0x8c, 0xa0, 0x80, 0x02, 0xad, 0x1f, 0x91, 0xac, 0x38, 0x71, 0xb4, 0x71, 0x40,
	0x40, 0x61, 0x8d, 0x77, 0x26, 0xeb, 0x51, 0xd6, 0x3b, 0xd6, 0xee, 0x38, 0x89, 0xf9, 0x02, 0xca,
	0x14, 0x14, 0x88, 0x0a, 0x89, 0x5f, 0x80, 0x7f, 0x48, 0x19, 0x51, 0x51, 0x01, 0x4a, 0x1a, 0x3e,
	0x82, 0x02, 0xed, 0xcb, 0xd8, 0x44, 0xca, 0xab, 0xa0, 0xf3, 0xf5, 0x3d, 0xe7, 0xdc, 0x39, 0xe7,
	0x5e, 0x69, 0xc1, 0x83, 0x3d, 0x66, 0x39, 0x9c, 0x98, 0x26, 0xe2, 0x94, 0x59, 0x25, 0x9d, 0xf5,
	0x07, 0x26, 0x45, 0x96, 0x4e, 0x4a, 0xfb, 0xab, 0x13, 0x55, 0x71, 0x60, 0x33, 0xce, 0xe0, 0x9d,
	0x29, 0x74, 0x71, 0xa2, 0xbf, 0xbf, 0x9a, 0x49, 0x1b, 0xcc, 0x60, 0x1e, 0xae, 0xe4, 0xfe, 0xf2,
	0x29, 0x99, 0x25, 0x9d, 0x39, 0x7d, 0xe6, 0x74, 0xfc, 0x86, 0x5f, 0x04, 0x2d, 0xc5, 0x60, 0xcc,
	0x30, 0x49, 0xc9, 0xab, 0xba, 0xc3, 0xdd, 0x12, 0x1e, 0xda, 0xbe, 0xb0, 0xdf, 0xcf, 0xfe, 0xdb,
	0xe7, 0xb4, 0x4f, 0x1c, 0x8e, 0xfa, 0x03, 0x1f, 0x90, 0xff, 0x2d, 0x80, 0xe8, 0x16, 0xb2, 0x51,
	0xdf, 0x81, 0x8f, 0x41, 0x02, 0x0d, 0x79, 0x8f, 0xd9, 0x94, 0x8f, 0x64, 0x21, 0x27, 0x14, 0x12,
	0x15, 0xf9, 0xeb, 0xe7, 0x95, 0x74, 0x30, 0x50, 0xc5, 0xd8, 0x26, 0x8e, 0xb3, 0xcd, 0x6d, 0x6a,
	0x19, 0xda, 0x5f, 0x28, 0x7c, 0x06, 0xe2, 0xae, 0xaa, 0xc9, 0xf4, 0x3d, 0x59, 0xcc, 0x09, 0x85,
	0xb9, 0xf2, 0x52, 0xd1, 0x1f, 0x5b, 0x0c, 0xc7, 0x16, 0x6b, 0xc1, 0xb3, 0x2a, 0xf1, 0xe3, 0xef,
	0xd9, 0xc8, 0xfb, 0x1f, 0x59, 0x41, 0x1b, 0x93, 0xe0, 0x4b, 0xb0, 0x88, 0x4c, 0x93, 0x1d, 0x98,
	0xd4, 0xe1, 0x1d, 0x84, 0x71, 0x67, 0x2c, 0x37, 0x73, 0x75, 0xb9, 0xf4, 0x58, 0x42, 0xc5, 0xb8,
	0x1d, 0x4a, 0xcb, 0x20, 0x46, 0xac, 0x5d, 0x66, 0xeb, 0x44, 0x96, 0x72, 0x42, 0x21, 0xae, 0x85,
	0xe5, 0x13, 0xe9, 0xd7, 0xc7, 0xac, 0x90, 0x7f, 0x27, 0x82, 0x44, 0x93, 0x3a, 0xbc, 0x6e, 0x71,
	0x7b, 0x04, 0xcb, 0x20, 0x86, 0x7c, 0x97, 0x97, 0xfa, 0x0f, 0x81, 0xf0, 0x11, 0x90, 0xdc, 0xa1,
	0x9e, 0xf3, 0x64, 0xf9, 0x6e, 0xf1, 0x82, 0xf5, 0x16, 0xdd, 0x49, 0x9a, 0x07, 0x77, 0x43, 0x43,
	0x18, 0x13, 0xdc, 0x41, 0x3c, 0x70, 0x99, 0x39, 0xe7, 0xb2, 0x1d, 0xee, 0xca, 0xb7, 0x79, 0xe4,
	0xda, 0x8c, 0x79, 0x2c, 0x95, 0xc3, 0x2a, 0x00, 0xe4, 0x70, 0x40, 0x6d, 0xe2, 0xb8, 0x12, 0xd2,
	0x95, 0x24, 0x04, 0x4f, 0x22, 0x11, 0xf0, 0x54, 0x0e, 0x17, 0x41, 0xd4, 0x26, 0xc8, 0x61, 0x96,
	0x3c, 0xeb, 0xfa, 0xd5, 0x82, 0x2a, 0x7f, 0x2c, 0x80, 0x68, 0xb5, 0x87, 0x2c, 0x83, 0xfc, 0xcf,
	0x4c, 0x9e, 0x82, 0x28, 0xd2, 0x5d, 0x88, 0x97, 0x48, 0xb2, 0x7c, 0xef, 0x42, 0xa2, 0xea, 0x41,
	0xb5, 0x80, 0x32, 0x61, 0x45, 0x9a, 0xb2, 0xf2, 0x45, 0x04, 0xf3, 0x5b, 0xc4, 0xc2, 0xd4, 0x32,
	0x76, 0x06, 0x18, 0x71, 0x02, 0x93, 0x40, 0xa4, 0xd8, 0x33, 0x23, 0x69, 0x22, 0xc5, 0xb0, 0x0a,
	0x62, 0xba, 0xe7, 0xd5, 0x91, 0xc5, 0xdc, 0x4c, 0x61, 0xee, 0x92, 0xb9, 0x7e, 0x2e, 0x15, 0xc9,
	0x5d, 0x89, 0x16, 0x32, 0xfd, 0x75, 0x10, 0x7d, 0xc8, 0xc9, 0x75, 0x37, 0x9a, 0x08, 0x78, 0xaa,
	0x1b, 0xc0, 0x2d, 0x47, 0xef, 0x11, 0x3c, 0x34, 0x09, 0xee, 0x74, 0x47, 0xb2, 0x74, 0x49, 0xe0,
	0x73, 0x63, 0x74, 0x65, 0x04, 0x37, 0x40, 0x9c, 0x1c, 0x72, 0x62, 0x61, 0x82, 0xe5, 0x59, 0xcf,
	0xc7, 0xfd, 0x0b, 0x7d, 0xd4, 0x03, 0xf0, 0x9a, 0x4d, 0xc8, 0x9b, 0xd0, 0xcf, 0x58, 0x22, 0xff,
	0x41, 0x00, 0xc9, 0x69, 0xc8, 0x8d, 0x4e, 0xa1, 0x0d, 0x6e, 0x33, 0x9b, 0x1a, 0xd4, 0x42, 0x66,
	0x67, 0xe2, 0x5e, 0xc5, 0x6b, 0x04, 0xb4, 0x10, 0x0a, 0xd4, 0xc3, 0xbb, 0xcd, 0xb7, 0x41, 0xbc,
	0xca, 0x98, 0x89, 0xd9, 0x81, 0x75, 0xa3, 0x57, 0xa5, 0xc1, 0xec, 0xd0, 0xe2, 0xd4, 0xf4, 0xde,
	0x31, 0xa3, 0xf9, 0xc5, 0x72, 0x05, 0x48, 0xee, 0x35, 0xc2, 0x34, 0x48, 0x35, 0x1b, 0xdb, 0xed,
	0xce, 0xce, 0xe6, 0xf6, 0x56, 0xbd, 0xda, 0x58, 0x6b, 0xd4, 0x6b, 0xa9, 0x08, 0x4c, 0x02, 0xe0,
	0xfd, 0xab, 0x36, 0x9b, 0xad, 0x17, 0x29, 0x61, 0x5c, 0x57, 0x9a, 0xad, 0xea, 0x7a, 0x4a, 0xcc,
	0x48, 0x6f, 0x3f, 0x29, 0x91, 0xe5, 0x06, 0x88, 0xaa, 0xe1, 0x41, 0x42, 0xb5, 0xda, 0x6e, 0xb4,
	0x36, 0xcf, 0xeb, 0x04, 0xff, 0xab, 0xb5, 0x5a, 0x4a, 0x80, 0x0b, 0x60, 0x3e, 0xa8, 0xb5, 0xfa,
	0x46, 0xeb, 0x79, 0x3d, 0x94, 0xaa, 0xbc, 0x3e, 0x3e, 0x55, 0x84, 0x93, 0x53, 0x45, 0xf8, 0x79,
	0xaa, 0x08, 0x47, 0x67, 0x4a, 0xe4, 0xe4, 0x4c, 0x89, 0x7c, 0x3b, 0x53, 0x22, 0xaf, 0x54, 0x83,
	0xf2, 0xde, 0xb0, 0xeb, 0x2e, 0xb4, 0xb4, 0x3e, 0xb9, 0xe2, 0x95, 0x4d, 0xc2, 0x0f, 0x98, 0xbd,
	0x57, 0x9a, 0xfe, 0x24, 0x1d, 0x4e, 0x7e, 0x94, 0xf8, 0x68, 0x40, 0x9c, 0x6e, 0xd4, 0x8b, 0xfc,
	0xe1, 0x9f, 0x01, 0x00, 0x3e, 0xce, 0x37, 0x4e, 0xbd, 0x06, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Authority != that1.Authority {
		return false
	}
	if this.Timelock != that1.Timelock {
		return false
	}
	if this.AllowlistAddTimelock != that1.AllowlistAddTimelock {
		return false
	}
	if this.Enforce != that1.Enforce {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enforce {
		i--
		if m.Enforce {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.AllowlistAddTimelock, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AllowlistAddTimelock):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintCompliance(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Timelock, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Timelock):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintCompliance(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ExpiresAt != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ExpiresAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExpiresAt):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintCompliance(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x22
	}
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.AddedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AddedAt):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintCompliance(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x1a
	if m.List != 0 {
		i = encodeVarintCompliance(dAtA, i, uint64(m.List))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Change) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Change) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Change) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	if m.Action != 0 {
		i = encodeVarintCompliance(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x18
	}
	if m.List != 0 {
		i = encodeVarintCompliance(dAtA, i, uint64(m.List))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Extended) > 0 {
		for iNdEx := len(m.Extended) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Extended[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCompliance(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ScheduledBy) > 0 {
		i -= len(m.ScheduledBy)
		copy(dAtA[i:], m.ScheduledBy)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.ScheduledBy)))
		i--
		dAtA[i] = 0x22
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExecuteAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExecuteAt):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintCompliance(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x1a
	if len(m.Changes) > 0 {
		for iNdEx := len(m.Changes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Changes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCompliance(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Id != 0 {
		i = encodeVarintCompliance(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ExtendedFreeze) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExtendedFreeze) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExtendedFreeze) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.OriginalExpiresAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.OriginalExpiresAt):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintCompliance(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Cooldown) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cooldown) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Cooldown) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Until != 0 {
		i = encodeVarintCompliance(dAtA, i, uint64(m.Until))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCompliance(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCompliance(dAtA []byte, offset int, v uint64) int {
	offset -= sovCompliance(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Timelock)
	n += 1 + l + sovCompliance(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AllowlistAddTimelock)
	n += 1 + l + sovCompliance(uint64(l))
	if m.Enforce {
		n += 2
	}
	return n
}

func (m *ListEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	if m.List != 0 {
		n += 1 + sovCompliance(uint64(m.List))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AddedAt)
	n += 1 + l + sovCompliance(uint64(l))
	if m.ExpiresAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExpiresAt)
		n += 1 + l + sovCompliance(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	return n
}

func (m *Change) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	if m.List != 0 {
		n += 1 + sovCompliance(uint64(m.List))
	}
	if m.Action != 0 {
		n += 1 + sovCompliance(uint64(m.Action))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	return n
}

func (m *PendingUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCompliance(uint64(m.Id))
	}
	if len(m.Changes) > 0 {
		for _, e := range m.Changes {
			l = e.Size()
			n += 1 + l + sovCompliance(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExecuteAt)
	n += 1 + l + sovCompliance(uint64(l))
	l = len(m.ScheduledBy)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	if len(m.Extended) > 0 {
		for _, e := range m.Extended {
			l = e.Size()
			n += 1 + l + sovCompliance(uint64(l))
		}
	}
	return n
}

func (m *ExtendedFreeze) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.OriginalExpiresAt)
	n += 1 + l + sovCompliance(uint64(l))
	return n
}

func (m *Cooldown) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCompliance(uint64(l))
	}
	if m.Until != 0 {
		n += 1 + sovCompliance(uint64(m.Until))
	}
	return n
}

func sovCompliance(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCompliance(x uint64) (n int) {
	return sovCompliance(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompliance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timelock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Timelock, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowlistAddTimelock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.AllowlistAddTimelock, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enforce", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enforce = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCompliance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompliance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompliance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			m.List = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.List |= List(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.AddedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiresAt == nil {
				m.ExpiresAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ExpiresAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompliance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompliance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Change) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompliance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Change: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Change: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			m.List = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.List |= List(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= Action(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompliance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompliance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompliance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Changes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Changes = append(m.Changes, Change{})
			if err := m.Changes[len(m.Changes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExecuteAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScheduledBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extended", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extended = append(m.Extended, ExtendedFreeze{})
			if err := m.Extended[len(m.Extended)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompliance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompliance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExtendedFreeze) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompliance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExtendedFreeze: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExtendedFreeze: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalExpiresAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.OriginalExpiresAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompliance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompliance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Cooldown) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompliance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cooldown: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cooldown: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompliance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCompliance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Until", wireType)
			}
			m.Until = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Until |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCompliance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCompliance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCompliance(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCompliance
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompliance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCompliance
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCompliance
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCompliance
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCompliance        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCompliance          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCompliance = fmt.Errorf("proto: unexpected end of group")
)
