// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: konstellation/compliance/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgScheduleUpdate queues changes behind the timelock.
type MsgScheduleUpdate struct {
	Authority string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Changes   []Change `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes"`
}

func (m *MsgScheduleUpdate) Reset()         { *m = MsgScheduleUpdate{} }
func (m *MsgScheduleUpdate) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleUpdate) ProtoMessage()    {}
func (*MsgScheduleUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{0}
}
func (m *MsgScheduleUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleUpdate.Merge(m, src)
}
func (m *MsgScheduleUpdate) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleUpdate proto.InternalMessageInfo

func (m *MsgScheduleUpdate) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgScheduleUpdate) GetChanges() []Change {
	if m != nil {
		return m.Changes
	}
	return nil
}

type MsgScheduleUpdateResponse struct {
	Id        uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecuteAt time.Time `protobuf:"bytes,2,opt,name=execute_at,json=executeAt,proto3,stdtime" json:"execute_at"`
}

func (m *MsgScheduleUpdateResponse) Reset()         { *m = MsgScheduleUpdateResponse{} }
func (m *MsgScheduleUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleUpdateResponse) ProtoMessage()    {}
func (*MsgScheduleUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{1}
}
func (m *MsgScheduleUpdateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleUpdateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleUpdateResponse.Merge(m, src)
}
func (m *MsgScheduleUpdateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleUpdateResponse proto.InternalMessageInfo

func (m *MsgScheduleUpdateResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgScheduleUpdateResponse) GetExecuteAt() time.Time {
	if m != nil {
		return m.ExecuteAt
	}
	return time.Time{}
}

// MsgCancelUpdate drops a pending update.
type MsgCancelUpdate struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Id        uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCancelUpdate) Reset()         { *m = MsgCancelUpdate{} }
func (m *MsgCancelUpdate) String() string { return proto.CompactTextString(m) }
func (*MsgCancelUpdate) ProtoMessage()    {}
func (*MsgCancelUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{2}
}
func (m *MsgCancelUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelUpdate.Merge(m, src)
}
func (m *MsgCancelUpdate) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelUpdate proto.InternalMessageInfo

func (m *MsgCancelUpdate) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCancelUpdate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCancelUpdateResponse struct {
}

func (m *MsgCancelUpdateResponse) Reset()         { *m = MsgCancelUpdateResponse{} }
func (m *MsgCancelUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelUpdateResponse) ProtoMessage()    {}
func (*MsgCancelUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{3}
}
func (m *MsgCancelUpdateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelUpdateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelUpdateResponse.Merge(m, src)
}
func (m *MsgCancelUpdateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelUpdateResponse proto.InternalMessageInfo

// MsgEmergencyFreeze freezes addresses now, for one timelock period.
type MsgEmergencyFreeze struct {
	Authority string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Reason    string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgEmergencyFreeze) Reset()         { *m = MsgEmergencyFreeze{} }
func (m *MsgEmergencyFreeze) String() string { return proto.CompactTextString(m) }
func (*MsgEmergencyFreeze) ProtoMessage()    {}
func (*MsgEmergencyFreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{4}
}
func (m *MsgEmergencyFreeze) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEmergencyFreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEmergencyFreeze.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEmergencyFreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEmergencyFreeze.Merge(m, src)
}
func (m *MsgEmergencyFreeze) XXX_Size() int {
	return m.Size()
}
func (m *MsgEmergencyFreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEmergencyFreeze.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEmergencyFreeze proto.InternalMessageInfo

func (m *MsgEmergencyFreeze) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgEmergencyFreeze) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *MsgEmergencyFreeze) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type MsgEmergencyFreezeResponse struct {
	ExpiresAt time.Time `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3,stdtime" json:"expires_at"`
}

func (m *MsgEmergencyFreezeResponse) Reset()         { *m = MsgEmergencyFreezeResponse{} }
func (m *MsgEmergencyFreezeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEmergencyFreezeResponse) ProtoMessage()    {}
func (*MsgEmergencyFreezeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{5}
}
func (m *MsgEmergencyFreezeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEmergencyFreezeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEmergencyFreezeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEmergencyFreezeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEmergencyFreezeResponse.Merge(m, src)
}
func (m *MsgEmergencyFreezeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEmergencyFreezeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEmergencyFreezeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEmergencyFreezeResponse proto.InternalMessageInfo

func (m *MsgEmergencyFreezeResponse) GetExpiresAt() time.Time {
	if m != nil {
		return m.ExpiresAt
	}
	return time.Time{}
}

// MsgLiftEmergencyFreeze ends emergency freezes early.
type MsgLiftEmergencyFreeze struct {
	Authority string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (m *MsgLiftEmergencyFreeze) Reset()         { *m = MsgLiftEmergencyFreeze{} }
func (m *MsgLiftEmergencyFreeze) String() string { return proto.CompactTextString(m) }
func (*MsgLiftEmergencyFreeze) ProtoMessage()    {}
func (*MsgLiftEmergencyFreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{6}
}
func (m *MsgLiftEmergencyFreeze) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiftEmergencyFreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiftEmergencyFreeze.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiftEmergencyFreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiftEmergencyFreeze.Merge(m, src)
}
func (m *MsgLiftEmergencyFreeze) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiftEmergencyFreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiftEmergencyFreeze.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiftEmergencyFreeze proto.InternalMessageInfo

func (m *MsgLiftEmergencyFreeze) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgLiftEmergencyFreeze) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type MsgLiftEmergencyFreezeResponse struct {
}

func (m *MsgLiftEmergencyFreezeResponse) Reset()         { *m = MsgLiftEmergencyFreezeResponse{} }
func (m *MsgLiftEmergencyFreezeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLiftEmergencyFreezeResponse) ProtoMessage()    {}
func (*MsgLiftEmergencyFreezeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{7}
}
func (m *MsgLiftEmergencyFreezeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiftEmergencyFreezeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiftEmergencyFreezeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiftEmergencyFreezeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiftEmergencyFreezeResponse.Merge(m, src)
}
func (m *MsgLiftEmergencyFreezeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiftEmergencyFreezeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiftEmergencyFreezeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiftEmergencyFreezeResponse proto.InternalMessageInfo

// MsgGovUpdate applies changes immediately. Governance only.
type MsgGovUpdate struct {
	Authority string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Changes   []Change `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes"`
}

func (m *MsgGovUpdate) Reset()         { *m = MsgGovUpdate{} }
func (m *MsgGovUpdate) String() string { return proto.CompactTextString(m) }
func (*MsgGovUpdate) ProtoMessage()    {}
func (*MsgGovUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{8}
}
func (m *MsgGovUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGovUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGovUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGovUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGovUpdate.Merge(m, src)
}
func (m *MsgGovUpdate) XXX_Size() int {
	return m.Size()
}
func (m *MsgGovUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGovUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGovUpdate proto.InternalMessageInfo

func (m *MsgGovUpdate) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgGovUpdate) GetChanges() []Change {
	if m != nil {
		return m.Changes
	}
	return nil
}

type MsgGovUpdateResponse struct {
}

func (m *MsgGovUpdateResponse) Reset()         { *m = MsgGovUpdateResponse{} }
func (m *MsgGovUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgGovUpdateResponse) ProtoMessage()    {}
func (*MsgGovUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{9}
}
func (m *MsgGovUpdateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGovUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGovUpdateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGovUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGovUpdateResponse.Merge(m, src)
}
func (m *MsgGovUpdateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgGovUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGovUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGovUpdateResponse proto.InternalMessageInfo

// MsgUpdateParams replaces the params. Governance only.
type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{10}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d66e40525a99db, []int{11}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgScheduleUpdate)(nil), "konstellation.compliance.v1.MsgScheduleUpdate")
	proto.RegisterType((*MsgScheduleUpdateResponse)(nil), "konstellation.compliance.v1.MsgScheduleUpdateResponse")
	proto.RegisterType((*MsgCancelUpdate)(nil), "konstellation.compliance.v1.MsgCancelUpdate")
	proto.RegisterType((*MsgCancelUpdateResponse)(nil), "konstellation.compliance.v1.MsgCancelUpdateResponse")
	proto.RegisterType((*MsgEmergencyFreeze)(nil), "konstellation.compliance.v1.MsgEmergencyFreeze")
	proto.RegisterType((*MsgEmergencyFreezeResponse)(nil), "konstellation.compliance.v1.MsgEmergencyFreezeResponse")
	proto.RegisterType((*MsgLiftEmergencyFreeze)(nil), "konstellation.compliance.v1.MsgLiftEmergencyFreeze")
	proto.RegisterType((*MsgLiftEmergencyFreezeResponse)(nil), "konstellation.compliance.v1.MsgLiftEmergencyFreezeResponse")
	proto.RegisterType((*MsgGovUpdate)(nil), "konstellation.compliance.v1.MsgGovUpdate")
	proto.RegisterType((*MsgGovUpdateResponse)(nil), "konstellation.compliance.v1.MsgGovUpdateResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "konstellation.compliance.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "konstellation.compliance.v1.MsgUpdateParamsResponse")
}

func init() {
	proto.RegisterFile("konstellation/compliance/v1/tx.proto", fileDescriptor_10d66e40525a99db)
}

var fileDescriptor_10d66e40525a99db = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x4f, 0x13, 0x5f,
	0x10, 0xef, 0x2b, 0x3f, 0xbe, 0xdf, 0x3e, 0x08, 0x84, 0x95, 0x40, 0x59, 0xcd, 0xb6, 0xae, 0xc6,
	0x20, 0x81, 0xdd, 0x50, 0x10, 0x63, 0x3d, 0xb5, 0x8d, 0x7a, 0xd0, 0x1a, 0x53, 0xf4, 0xa2, 0x07,
	0xb2, 0x6c, 0x1f, 0xaf, 0x1b, 0x76, 0xf7, 0x6d, 0xf6, 0xbd, 0x62, 0xd1, 0x8b, 0xf1, 0x62, 0x62,
	0x62, 0xc2, 0x9f, 0xc2, 0xc1, 0xa3, 0x07, 0x13, 0x13, 0xc3, 0x91, 0xe8, 0xc5, 0x93, 0x12, 0x38,
	0xf0, 0x6f, 0x98, 0xfd, 0xd9, 0x6d, 0x77, 0xd3, 0xd2, 0x7a, 0xd0, 0x0b, 0x61, 0xe6, 0x7d, 0x66,
	0xe6, 0xf3, 0x99, 0xe9, 0x4c, 0x0b, 0xaf, 0xef, 0x12, 0x93, 0x32, 0xa4, 0xeb, 0x0a, 0xd3, 0x88,
	0x29, 0xab, 0xc4, 0xb0, 0x74, 0x4d, 0x31, 0x55, 0x24, 0xef, 0xad, 0xca, 0xac, 0x25, 0x59, 0x36,
	0x61, 0x84, 0xbb, 0xdc, 0x81, 0x92, 0xda, 0x28, 0x69, 0x6f, 0x95, 0x9f, 0xc5, 0x04, 0x13, 0x17,
	0x27, 0x3b, 0xff, 0x79, 0x21, 0xfc, 0x82, 0x4a, 0xa8, 0x41, 0xe8, 0x96, 0xf7, 0xe0, 0x19, 0xfe,
	0xd3, 0xbc, 0x67, 0xc9, 0x06, 0xc5, 0x4e, 0x15, 0x83, 0x62, 0xff, 0x61, 0x46, 0x31, 0x34, 0x93,
	0xc8, 0xee, 0x5f, 0xdf, 0x95, 0xc3, 0x84, 0x60, 0x1d, 0xc9, 0xae, 0xb5, 0xdd, 0xdc, 0x91, 0x99,
	0x66, 0x20, 0xca, 0x14, 0xc3, 0xf2, 0x01, 0xcb, 0xbd, 0x04, 0xb4, 0x2d, 0x0f, 0x2d, 0x7e, 0x05,
	0x70, 0xa6, 0x4a, 0xf1, 0xa6, 0xda, 0x40, 0xf5, 0xa6, 0x8e, 0x9e, 0x59, 0x75, 0x85, 0x21, 0x6e,
	0x03, 0x66, 0x94, 0x26, 0x6b, 0x10, 0x5b, 0x63, 0xfb, 0x59, 0x90, 0x07, 0x8b, 0x99, 0x72, 0xf6,
	0xdb, 0xc7, 0x95, 0x59, 0x9f, 0x75, 0xa9, 0x5e, 0xb7, 0x11, 0xa5, 0x9b, 0xcc, 0xd6, 0x4c, 0x5c,
	0x6b, 0x43, 0xb9, 0x0a, 0xfc, 0x4f, 0x6d, 0x28, 0x26, 0x46, 0x34, 0x9b, 0xce, 0x8f, 0x2c, 0x4e,
	0x14, 0xae, 0x49, 0x3d, 0x1a, 0x25, 0x55, 0x5c, 0x6c, 0x79, 0xf4, 0xe8, 0x67, 0x2e, 0x55, 0x0b,
	0x22, 0x8b, 0xeb, 0x6f, 0xcf, 0x0f, 0x97, 0xda, 0x49, 0xdf, 0x9f, 0x1f, 0x2e, 0x5d, 0x75, 0xb2,
	0x44, 0xa5, 0xc4, 0x28, 0x8b, 0x16, 0x5c, 0x88, 0x39, 0x6b, 0x88, 0x5a, 0xc4, 0xa4, 0x88, 0x9b,
	0x82, 0x69, 0xad, 0xee, 0x0a, 0x19, 0xad, 0xa5, 0xb5, 0x3a, 0x57, 0x81, 0x10, 0xb5, 0x90, 0xda,
	0x64, 0x68, 0x4b, 0x61, 0xd9, 0x74, 0x1e, 0x2c, 0x4e, 0x14, 0x78, 0xc9, 0xeb, 0xac, 0x14, 0x74,
	0x56, 0x7a, 0x1a, 0x74, 0xb6, 0xfc, 0xbf, 0xc3, 0xf0, 0xe0, 0x57, 0x0e, 0xd4, 0x32, 0x7e, 0x5c,
	0x89, 0x89, 0x1f, 0x00, 0x9c, 0xae, 0x52, 0x5c, 0x71, 0x08, 0xe9, 0x7f, 0xd8, 0x38, 0x8f, 0x60,
	0x3a, 0x20, 0x58, 0x2c, 0xc4, 0x7b, 0x90, 0x4b, 0xe8, 0x41, 0xb4, 0xb6, 0xb8, 0x00, 0xe7, 0xbb,
	0x5c, 0x81, 0x7e, 0xf1, 0x3b, 0x80, 0x5c, 0x95, 0xe2, 0x7b, 0x06, 0xb2, 0x31, 0x32, 0xd5, 0xfd,
	0xfb, 0x36, 0x42, 0xaf, 0x86, 0x67, 0xeb, 0xc4, 0x79, 0x6f, 0xfe, 0xa0, 0x7b, 0xc7, 0x05, 0x50,
	0x6e, 0x0e, 0x8e, 0xdb, 0x48, 0xa1, 0xc4, 0xcc, 0x8e, 0x38, 0xc5, 0x6a, 0xbe, 0x55, 0xbc, 0x15,
	0x57, 0x2b, 0x26, 0xa8, 0xed, 0xa2, 0x2f, 0x2a, 0x90, 0x8f, 0x7b, 0xc3, 0x99, 0xbb, 0x33, 0xb6,
	0x34, 0x1b, 0x51, 0x67, 0xc6, 0x60, 0xb0, 0x19, 0xbb, 0x71, 0x25, 0x26, 0x7e, 0x01, 0x70, 0xae,
	0x4a, 0xf1, 0x23, 0x6d, 0x87, 0xfd, 0xe5, 0xe6, 0x15, 0xef, 0xc4, 0x9b, 0x74, 0x23, 0xa1, 0x49,
	0x09, 0x54, 0xc5, 0x3c, 0x14, 0x92, 0x5f, 0xc2, 0x0f, 0xc8, 0x27, 0x00, 0x27, 0xab, 0x14, 0x3f,
	0x20, 0x7b, 0xff, 0xc2, 0x05, 0x90, 0xe3, 0x52, 0xaf, 0x24, 0x48, 0x0d, 0xd9, 0x8a, 0x73, 0x70,
	0x36, 0x6a, 0x87, 0xb2, 0x3e, 0x7b, 0x2b, 0xea, 0x79, 0x9f, 0x28, 0xb6, 0x62, 0xd0, 0xa1, 0x95,
	0x95, 0xe0, 0xb8, 0xe5, 0x66, 0xf0, 0xef, 0x45, 0x6f, 0x61, 0x5e, 0x31, 0x5f, 0x98, 0x1f, 0x78,
	0xd1, 0xad, 0x8e, 0xd2, 0xf5, 0xb7, 0x3a, 0xea, 0x0a, 0xd4, 0x15, 0x4e, 0xc6, 0xe0, 0x48, 0x95,
	0x62, 0xae, 0x05, 0xa7, 0xba, 0xee, 0xb7, 0xd4, 0x93, 0x5b, 0xec, 0x4e, 0xf2, 0x1b, 0x83, 0xe1,
	0xc3, 0x1d, 0xb3, 0xe1, 0x64, 0xc7, 0xf9, 0x5b, 0xee, 0x97, 0x27, 0x8a, 0xe6, 0xd7, 0x07, 0x41,
	0x87, 0x35, 0x5f, 0xc3, 0xe9, 0xee, 0x55, 0x94, 0xfb, 0x25, 0xea, 0x0a, 0xe0, 0x6f, 0x0f, 0x18,
	0x10, 0x16, 0x7f, 0x07, 0xe0, 0xa5, 0xa4, 0x63, 0xb0, 0xd6, 0x2f, 0x61, 0x42, 0x10, 0x7f, 0x77,
	0x88, 0xa0, 0x90, 0x89, 0x06, 0x33, 0xed, 0x6d, 0xbd, 0xd9, 0x2f, 0x53, 0x08, 0xe5, 0x57, 0x2f,
	0x0c, 0x8d, 0x4e, 0xb9, 0x63, 0x83, 0xfa, 0x4e, 0x39, 0x8a, 0xe6, 0xd7, 0x07, 0x41, 0x07, 0x35,
	0xf9, 0xb1, 0x37, 0xe7, 0x87, 0x4b, 0xa0, 0xfc, 0xe2, 0xe8, 0x54, 0x00, 0xc7, 0xa7, 0x02, 0x38,
	0x39, 0x15, 0xc0, 0xc1, 0x99, 0x90, 0x3a, 0x3e, 0x13, 0x52, 0x3f, 0xce, 0x84, 0xd4, 0xf3, 0x12,
	0xd6, 0x58, 0xa3, 0xb9, 0xed, 0xa4, 0x93, 0x1f, 0x46, 0x0b, 0xac, 0x3c, 0x46, 0xec, 0x25, 0xb1,
	0x77, 0xe5, 0xce, 0xdf, 0x41, 0xad, 0xe8, 0x92, 0xb1, 0x7d, 0x0b, 0xd1, 0xed, 0x71, 0xf7, 0x5b,
	0x60, 0xed, 0xf7, 0x00, 0x0c, 0x0f, 0x2d, 0xd8, 0xf3, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ScheduleUpdate (list authority) queues changes that take effect after the
	// timelock. Cancellable until then.
	ScheduleUpdate(ctx context.Context, in *MsgScheduleUpdate, opts ...grpc.CallOption) (*MsgScheduleUpdateResponse, error)
	// CancelUpdate (list authority or governance) drops a pending update.
	CancelUpdate(ctx context.Context, in *MsgCancelUpdate, opts ...grpc.CallOption) (*MsgCancelUpdateResponse, error)
	// EmergencyFreeze (list authority) freezes addresses immediately for one
	// timelock period. To make it permanent, ScheduleUpdate an ACTION_ADD to
	// LIST_BLOCK before it expires, or have governance do it.
	EmergencyFreeze(ctx context.Context, in *MsgEmergencyFreeze, opts ...grpc.CallOption) (*MsgEmergencyFreezeResponse, error)
	// LiftEmergencyFreeze (list authority or governance) ends an emergency
	// freeze early. Permanent entries are not affected.
	LiftEmergencyFreeze(ctx context.Context, in *MsgLiftEmergencyFreeze, opts ...grpc.CallOption) (*MsgLiftEmergencyFreezeResponse, error)
	// GovUpdate (governance only) applies changes immediately: the override.
	GovUpdate(ctx context.Context, in *MsgGovUpdate, opts ...grpc.CallOption) (*MsgGovUpdateResponse, error)
	// UpdateParams (governance only) replaces the params, including who the
	// list authority is.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ScheduleUpdate(ctx context.Context, in *MsgScheduleUpdate, opts ...grpc.CallOption) (*MsgScheduleUpdateResponse, error) {
	out := new(MsgScheduleUpdateResponse)
	err := c.cc.Invoke(ctx, "/konstellation.compliance.v1.Msg/ScheduleUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelUpdate(ctx context.Context, in *MsgCancelUpdate, opts ...grpc.CallOption) (*MsgCancelUpdateResponse, error) {
	out := new(MsgCancelUpdateResponse)
	err := c.cc.Invoke(ctx, "/konstellation.compliance.v1.Msg/CancelUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EmergencyFreeze(ctx context.Context, in *MsgEmergencyFreeze, opts ...grpc.CallOption) (*MsgEmergencyFreezeResponse, error) {
	out := new(MsgEmergencyFreezeResponse)
	err := c.cc.Invoke(ctx, "/konstellation.compliance.v1.Msg/EmergencyFreeze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LiftEmergencyFreeze(ctx context.Context, in *MsgLiftEmergencyFreeze, opts ...grpc.CallOption) (*MsgLiftEmergencyFreezeResponse, error) {
	out := new(MsgLiftEmergencyFreezeResponse)
	err := c.cc.Invoke(ctx, "/konstellation.compliance.v1.Msg/LiftEmergencyFreeze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GovUpdate(ctx context.Context, in *MsgGovUpdate, opts ...grpc.CallOption) (*MsgGovUpdateResponse, error) {
	out := new(MsgGovUpdateResponse)
	err := c.cc.Invoke(ctx, "/konstellation.compliance.v1.Msg/GovUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/konstellation.compliance.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ScheduleUpdate (list authority) queues changes that take effect after the
	// timelock. Cancellable until then.
	ScheduleUpdate(context.Context, *MsgScheduleUpdate) (*MsgScheduleUpdateResponse, error)
	// CancelUpdate (list authority or governance) drops a pending update.
	CancelUpdate(context.Context, *MsgCancelUpdate) (*MsgCancelUpdateResponse, error)
	// EmergencyFreeze (list authority) freezes addresses immediately for one
	// timelock period. To make it permanent, ScheduleUpdate an ACTION_ADD to
	// LIST_BLOCK before it expires, or have governance do it.
	EmergencyFreeze(context.Context, *MsgEmergencyFreeze) (*MsgEmergencyFreezeResponse, error)
	// LiftEmergencyFreeze (list authority or governance) ends an emergency
	// freeze early. Permanent entries are not affected.
	LiftEmergencyFreeze(context.Context, *MsgLiftEmergencyFreeze) (*MsgLiftEmergencyFreezeResponse, error)
	// GovUpdate (governance only) applies changes immediately: the override.
	GovUpdate(context.Context, *MsgGovUpdate) (*MsgGovUpdateResponse, error)
	// UpdateParams (governance only) replaces the params, including who the
	// list authority is.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ScheduleUpdate(ctx context.Context, req *MsgScheduleUpdate) (*MsgScheduleUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleUpdate not implemented")
}
func (*UnimplementedMsgServer) CancelUpdate(ctx context.Context, req *MsgCancelUpdate) (*MsgCancelUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelUpdate not implemented")
}
func (*UnimplementedMsgServer) EmergencyFreeze(ctx context.Context, req *MsgEmergencyFreeze) (*MsgEmergencyFreezeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyFreeze not implemented")
}
func (*UnimplementedMsgServer) LiftEmergencyFreeze(ctx context.Context, req *MsgLiftEmergencyFreeze) (*MsgLiftEmergencyFreezeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiftEmergencyFreeze not implemented")
}
func (*UnimplementedMsgServer) GovUpdate(ctx context.Context, req *MsgGovUpdate) (*MsgGovUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GovUpdate not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ScheduleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgScheduleUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ScheduleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.compliance.v1.Msg/ScheduleUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ScheduleUpdate(ctx, req.(*MsgScheduleUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.compliance.v1.Msg/CancelUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelUpdate(ctx, req.(*MsgCancelUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EmergencyFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEmergencyFreeze)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EmergencyFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.compliance.v1.Msg/EmergencyFreeze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EmergencyFreeze(ctx, req.(*MsgEmergencyFreeze))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LiftEmergencyFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLiftEmergencyFreeze)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LiftEmergencyFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.compliance.v1.Msg/LiftEmergencyFreeze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LiftEmergencyFreeze(ctx, req.(*MsgLiftEmergencyFreeze))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GovUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGovUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GovUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.compliance.v1.Msg/GovUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GovUpdate(ctx, req.(*MsgGovUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.compliance.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "konstellation.compliance.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleUpdate",
			Handler:    _Msg_ScheduleUpdate_Handler,
		},
		{
			MethodName: "CancelUpdate",
			Handler:    _Msg_CancelUpdate_Handler,
		},
		{
			MethodName: "EmergencyFreeze",
			Handler:    _Msg_EmergencyFreeze_Handler,
		},
		{
			MethodName: "LiftEmergencyFreeze",
			Handler:    _Msg_LiftEmergencyFreeze_Handler,
		},
		{
			MethodName: "GovUpdate",
			Handler:    _Msg_GovUpdate_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "konstellation/compliance/v1/tx.proto",
}

func (m *MsgScheduleUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Changes) > 0 {
		for iNdEx := len(m.Changes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Changes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgScheduleUpdateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleUpdateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleUpdateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExecuteAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExecuteAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTx(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelUpdateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelUpdateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelUpdateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgEmergencyFreeze) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEmergencyFreeze) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEmergencyFreeze) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEmergencyFreezeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEmergencyFreezeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEmergencyFreezeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExpiresAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpiresAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTx(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgLiftEmergencyFreeze) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiftEmergencyFreeze) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiftEmergencyFreeze) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLiftEmergencyFreezeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiftEmergencyFreezeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiftEmergencyFreezeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgGovUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGovUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGovUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Changes) > 0 {
		for iNdEx := len(m.Changes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Changes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgGovUpdateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGovUpdateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGovUpdateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgScheduleUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Changes) > 0 {
		for _, e := range m.Changes {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgScheduleUpdateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExecuteAt)
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCancelUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCancelUpdateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgEmergencyFreeze) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgEmergencyFreezeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpiresAt)
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgLiftEmergencyFreeze) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgLiftEmergencyFreezeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgGovUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Changes) > 0 {
		for _, e := range m.Changes {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgGovUpdateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgScheduleUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Changes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Changes = append(m.Changes, Change{})
			if err := m.Changes[len(m.Changes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgScheduleUpdateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleUpdateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleUpdateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExecuteAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelUpdateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelUpdateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelUpdateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEmergencyFreeze) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEmergencyFreeze: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEmergencyFreeze: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEmergencyFreezeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEmergencyFreezeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEmergencyFreezeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExpiresAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiftEmergencyFreeze) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiftEmergencyFreeze: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiftEmergencyFreeze: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiftEmergencyFreezeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiftEmergencyFreezeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiftEmergencyFreezeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGovUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGovUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGovUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Changes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Changes = append(m.Changes, Change{})
			if err := m.Changes[len(m.Changes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGovUpdateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGovUpdateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGovUpdateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
