// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: konstellation/ratelimit/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryRateLimitsRequest struct {
}

func (m *QueryRateLimitsRequest) Reset()         { *m = QueryRateLimitsRequest{} }
func (m *QueryRateLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsRequest) ProtoMessage()    {}
func (*QueryRateLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac569ad1d730369, []int{0}
}
func (m *QueryRateLimitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsRequest.Merge(m, src)
}
func (m *QueryRateLimitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsRequest proto.InternalMessageInfo

type QueryRateLimitsResponse struct {
	RateLimits []RateLimit `protobuf:"bytes,1,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits"`
}

func (m *QueryRateLimitsResponse) Reset()         { *m = QueryRateLimitsResponse{} }
func (m *QueryRateLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsResponse) ProtoMessage()    {}
func (*QueryRateLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac569ad1d730369, []int{1}
}
func (m *QueryRateLimitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsResponse.Merge(m, src)
}
func (m *QueryRateLimitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsResponse proto.InternalMessageInfo

func (m *QueryRateLimitsResponse) GetRateLimits() []RateLimit {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

type QueryRateLimitRequest struct {
	Denom     string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *QueryRateLimitRequest) Reset()         { *m = QueryRateLimitRequest{} }
func (m *QueryRateLimitRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitRequest) ProtoMessage()    {}
func (*QueryRateLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac569ad1d730369, []int{2}
}
func (m *QueryRateLimitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitRequest.Merge(m, src)
}
func (m *QueryRateLimitRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitRequest proto.InternalMessageInfo

func (m *QueryRateLimitRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryRateLimitRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type QueryRateLimitResponse struct {
	RateLimit *RateLimit `protobuf:"bytes,1,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
}

func (m *QueryRateLimitResponse) Reset()         { *m = QueryRateLimitResponse{} }
func (m *QueryRateLimitResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitResponse) ProtoMessage()    {}
func (*QueryRateLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac569ad1d730369, []int{3}
}
func (m *QueryRateLimitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitResponse.Merge(m, src)
}
func (m *QueryRateLimitResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitResponse proto.InternalMessageInfo

func (m *QueryRateLimitResponse) GetRateLimit() *RateLimit {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

type QueryRateLimitsByChannelRequest struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *QueryRateLimitsByChannelRequest) Reset()         { *m = QueryRateLimitsByChannelRequest{} }
func (m *QueryRateLimitsByChannelRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsByChannelRequest) ProtoMessage()    {}
func (*QueryRateLimitsByChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac569ad1d730369, []int{4}
}
func (m *QueryRateLimitsByChannelRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsByChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsByChannelRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsByChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsByChannelRequest.Merge(m, src)
}
func (m *QueryRateLimitsByChannelRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsByChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsByChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsByChannelRequest proto.InternalMessageInfo

func (m *QueryRateLimitsByChannelRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type QueryRateLimitsByChannelResponse struct {
	RateLimits []RateLimit `protobuf:"bytes,1,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits"`
}

func (m *QueryRateLimitsByChannelResponse) Reset()         { *m = QueryRateLimitsByChannelResponse{} }
func (m *QueryRateLimitsByChannelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitsByChannelResponse) ProtoMessage()    {}
func (*QueryRateLimitsByChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fac569ad1d730369, []int{5}
}
func (m *QueryRateLimitsByChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitsByChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitsByChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitsByChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitsByChannelResponse.Merge(m, src)
}
func (m *QueryRateLimitsByChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitsByChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitsByChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitsByChannelResponse proto.InternalMessageInfo

func (m *QueryRateLimitsByChannelResponse) GetRateLimits() []RateLimit {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRateLimitsRequest)(nil), "konstellation.ratelimit.v1.QueryRateLimitsRequest")
	proto.RegisterType((*QueryRateLimitsResponse)(nil), "konstellation.ratelimit.v1.QueryRateLimitsResponse")
	proto.RegisterType((*QueryRateLimitRequest)(nil), "konstellation.ratelimit.v1.QueryRateLimitRequest")
	proto.RegisterType((*QueryRateLimitResponse)(nil), "konstellation.ratelimit.v1.QueryRateLimitResponse")
	proto.RegisterType((*QueryRateLimitsByChannelRequest)(nil), "konstellation.ratelimit.v1.QueryRateLimitsByChannelRequest")
	proto.RegisterType((*QueryRateLimitsByChannelResponse)(nil), "konstellation.ratelimit.v1.QueryRateLimitsByChannelResponse")
}

func init() {
	proto.RegisterFile("konstellation/ratelimit/v1/query.proto", fileDescriptor_fac569ad1d730369)
}

var fileDescriptor_fac569ad1d730369 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x33, 0xb5, 0x15, 0xf2, 0x7a, 0x1b, 0xab, 0x86, 0xa0, 0xe9, 0x12, 0x50, 0xeb, 0x82,
	0x19, 0x36, 0x15, 0x2f, 0x56, 0x59, 0x56, 0x11, 0xc4, 0x45, 0x30, 0xc7, 0x1e, 0x2c, 0x69, 0x77,
	0x48, 0x43, 0xb3, 0x33, 0x69, 0x66, 0xb6, 0xba, 0x94, 0x5e, 0xfc, 0x04, 0x82, 0xdf, 0xc1, 0x0f,
	0xe1, 0xc1, 0x73, 0x4f, 0x52, 0xf0, 0xe2, 0x49, 0x64, 0xd7, 0x0f, 0x22, 0x99, 0xa4, 0x49, 0x13,
	0xdb, 0x35, 0x2b, 0xf4, 0xb6, 0x3b, 0xf3, 0xde, 0xff, 0xff, 0xfb, 0xcf, 0x7b, 0x04, 0xee, 0xee,
	0x71, 0x26, 0x24, 0x8d, 0x22, 0x5f, 0x86, 0x9c, 0x91, 0xc4, 0x97, 0x34, 0x0a, 0x87, 0xa1, 0x24,
	0x07, 0x1d, 0xb2, 0x3f, 0xa2, 0xc9, 0xd8, 0x89, 0x13, 0x2e, 0x39, 0x36, 0x2b, 0x75, 0x4e, 0x51,
	0xe7, 0x1c, 0x74, 0xcc, 0x95, 0x80, 0x07, 0x5c, 0x95, 0x91, 0xf4, 0x57, 0xd6, 0x61, 0xde, 0x0a,
	0x38, 0x0f, 0x22, 0x4a, 0xfc, 0x38, 0x24, 0x3e, 0x63, 0x5c, 0xaa, 0x4e, 0x91, 0xdf, 0xb6, 0x67,
	0xf8, 0x96, 0xe2, 0xaa, 0xd6, 0x36, 0xe0, 0xc6, 0x9b, 0x14, 0xc5, 0xf3, 0x25, 0xed, 0xa7, 0xe7,
	0xc2, 0xa3, 0xfb, 0x23, 0x2a, 0xa4, 0x1d, 0xc0, 0xcd, 0xbf, 0x6e, 0x44, 0xcc, 0x99, 0xa0, 0xb8,
	0x0f, 0xcb, 0xa9, 0xce, 0x96, 0x12, 0x12, 0x06, 0x6a, 0x5d, 0x59, 0x5b, 0x76, 0xef, 0x38, 0x17,
	0xc7, 0x70, 0x0a, 0x91, 0xde, 0xe2, 0xf1, 0xcf, 0x55, 0xcd, 0x83, 0xa4, 0x50, 0xb5, 0xfb, 0x70,
	0xbd, 0x6a, 0x94, 0x13, 0xe0, 0x15, 0x58, 0x1a, 0x50, 0xc6, 0x87, 0x06, 0x6a, 0xa1, 0x35, 0xdd,
	0xcb, 0xfe, 0xe0, 0xdb, 0x00, 0x3b, 0xbb, 0x3e, 0x63, 0x34, 0xda, 0x0a, 0x07, 0xc6, 0x82, 0xba,
	0xd2, 0xf3, 0x93, 0x97, 0x03, 0xfb, 0x6d, 0x3d, 0x50, 0x41, 0xfd, 0x1c, 0xa0, 0xa4, 0x56, 0x9a,
	0x4d, 0xa1, 0x3d, 0xbd, 0xc0, 0xb5, 0xbb, 0xb0, 0x5a, 0x7b, 0x96, 0xde, 0xf8, 0x59, 0xe6, 0x7e,
	0xca, 0x5d, 0x25, 0x44, 0x75, 0xc2, 0x18, 0x5a, 0x17, 0x2b, 0x5c, 0xc6, 0x0b, 0xbb, 0x5f, 0x17,
	0x61, 0x49, 0x59, 0xe2, 0xcf, 0x08, 0xa0, 0xf4, 0xc5, 0xee, 0x2c, 0xc5, 0xf3, 0xf7, 0xc2, 0x5c,
	0x9f, 0xab, 0x27, 0xcb, 0x63, 0x93, 0x0f, 0xdf, 0x7f, 0x7f, 0x5a, 0xb8, 0x8f, 0xef, 0x91, 0x7f,
	0xec, 0x66, 0x9e, 0x18, 0x7f, 0x41, 0xa0, 0x17, 0x3a, 0xb8, 0xd3, 0xdc, 0xf3, 0x14, 0xd3, 0x9d,
	0xa7, 0x25, 0xa7, 0x7c, 0xa1, 0x28, 0xbb, 0xf8, 0x69, 0x33, 0x4a, 0x72, 0x58, 0x8e, 0xf9, 0x88,
	0x1c, 0xaa, 0xf5, 0x7c, 0xd2, 0x6e, 0x1f, 0xe1, 0x6f, 0x08, 0xae, 0x9d, 0x33, 0x5d, 0xfc, 0x78,
	0x8e, 0xa7, 0xab, 0x6f, 0x95, 0xb9, 0xf1, 0x7f, 0xcd, 0x79, 0xb4, 0x0d, 0x15, 0xed, 0x11, 0x7e,
	0xd8, 0x70, 0x00, 0x95, 0x6c, 0xbd, 0xcd, 0xe3, 0x89, 0x85, 0x4e, 0x26, 0x16, 0xfa, 0x35, 0xb1,
	0xd0, 0xc7, 0xa9, 0xa5, 0x9d, 0x4c, 0x2d, 0xed, 0xc7, 0xd4, 0xd2, 0x36, 0xbb, 0x41, 0x28, 0x77,
	0x47, 0xdb, 0xce, 0x0e, 0x1f, 0x92, 0x57, 0x67, 0x95, 0x1f, 0xbc, 0xa6, 0xf2, 0x1d, 0x4f, 0xf6,
	0x6a, 0x7e, 0xef, 0xcf, 0x38, 0xca, 0x71, 0x4c, 0xc5, 0xf6, 0x55, 0xf5, 0x21, 0x5a, 0xff, 0x33,
	0x00, 0x93, 0x52, 0x5c, 0xda, 0x2e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// RateLimits lists every rate limit.
	RateLimits(ctx context.Context, in *QueryRateLimitsRequest, opts ...grpc.CallOption) (*QueryRateLimitsResponse, error)
	// RateLimit returns one path's limit and flow.
	RateLimit(ctx context.Context, in *QueryRateLimitRequest, opts ...grpc.CallOption) (*QueryRateLimitResponse, error)
	// RateLimitsByChannel lists the limits on one channel.
	RateLimitsByChannel(ctx context.Context, in *QueryRateLimitsByChannelRequest, opts ...grpc.CallOption) (*QueryRateLimitsByChannelResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RateLimits(ctx context.Context, in *QueryRateLimitsRequest, opts ...grpc.CallOption) (*QueryRateLimitsResponse, error) {
	out := new(QueryRateLimitsResponse)
	err := c.cc.Invoke(ctx, "/konstellation.ratelimit.v1.Query/RateLimits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RateLimit(ctx context.Context, in *QueryRateLimitRequest, opts ...grpc.CallOption) (*QueryRateLimitResponse, error) {
	out := new(QueryRateLimitResponse)
	err := c.cc.Invoke(ctx, "/konstellation.ratelimit.v1.Query/RateLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RateLimitsByChannel(ctx context.Context, in *QueryRateLimitsByChannelRequest, opts ...grpc.CallOption) (*QueryRateLimitsByChannelResponse, error) {
	out := new(QueryRateLimitsByChannelResponse)
	err := c.cc.Invoke(ctx, "/konstellation.ratelimit.v1.Query/RateLimitsByChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// RateLimits lists every rate limit.
	RateLimits(context.Context, *QueryRateLimitsRequest) (*QueryRateLimitsResponse, error)
	// RateLimit returns one path's limit and flow.
	RateLimit(context.Context, *QueryRateLimitRequest) (*QueryRateLimitResponse, error)
	// RateLimitsByChannel lists the limits on one channel.
	RateLimitsByChannel(context.Context, *QueryRateLimitsByChannelRequest) (*QueryRateLimitsByChannelResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) RateLimits(ctx context.Context, req *QueryRateLimitsRequest) (*QueryRateLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateLimits not implemented")
}
func (*UnimplementedQueryServer) RateLimit(ctx context.Context, req *QueryRateLimitRequest) (*QueryRateLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateLimit not implemented")
}
func (*UnimplementedQueryServer) RateLimitsByChannel(ctx context.Context, req *QueryRateLimitsByChannelRequest) (*QueryRateLimitsByChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateLimitsByChannel not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_RateLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RateLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.ratelimit.v1.Query/RateLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RateLimits(ctx, req.(*QueryRateLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.ratelimit.v1.Query/RateLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RateLimit(ctx, req.(*QueryRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RateLimitsByChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitsByChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RateLimitsByChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konstellation.ratelimit.v1.Query/RateLimitsByChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RateLimitsByChannel(ctx, req.(*QueryRateLimitsByChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "konstellation.ratelimit.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RateLimits",
			Handler:    _Query_RateLimits_Handler,
		},
		{
			MethodName: "RateLimit",
			Handler:    _Query_RateLimit_Handler,
		},
		{
			MethodName: "RateLimitsByChannel",
			Handler:    _Query_RateLimitsByChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "konstellation/ratelimit/v1/query.proto",
}

func (m *QueryRateLimitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for iNdEx := len(m.RateLimits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RateLimits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RateLimit != nil {
		{
			size, err := m.RateLimit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitsByChannelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsByChannelRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsByChannelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitsByChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitsByChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitsByChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for iNdEx := len(m.RateLimits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RateLimits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRateLimitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRateLimitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for _, e := range m.RateLimits {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryRateLimitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRateLimitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RateLimit != nil {
		l = m.RateLimit.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRateLimitsByChannelRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRateLimitsByChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RateLimits) > 0 {
		for _, e := range m.RateLimits {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRateLimitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RateLimits = append(m.RateLimits, RateLimit{})
			if err := m.RateLimits[len(m.RateLimits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RateLimit == nil {
				m.RateLimit = &RateLimit{}
			}
			if err := m.RateLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitsByChannelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitsByChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitsByChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RateLimits = append(m.RateLimits, RateLimit{})
			if err := m.RateLimits[len(m.RateLimits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
